FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y wget

# installing xpra
# see manual here: https://github.com/Xpra-org/xpra/wiki/Download#-for-debian-based-distributions
# "Ubuntu 24.04 - Noble Nombat"|"Stable Repository File" is used here
RUN apt install -y apt-transport-https software-properties-common

RUN apt install -y ca-certificates
RUN wget -O "/usr/share/keyrings/xpra.asc" https://xpra.org/xpra.asc
WORKDIR /etc/apt/sources.list.d
RUN wget https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/noble/xpra.sources

RUN apt update && \
    apt install -y xpra
WORKDIR /


# installing scrcpy
# see manual here: 
# https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#from-an-install-script
# for Debian/Ubuntu
RUN apt install -y ffmpeg libsdl2-2.0-0 adb wget \
                 gcc git pkg-config meson ninja-build libsdl2-dev \
                 libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
                 libswresample-dev libusb-1.0-0 libusb-1.0-0-dev

# additional sudo will required
RUN apt install -y sudo

RUN git clone --depth 1 https://github.com/Genymobile/scrcpy
WORKDIR /scrcpy
RUN /scrcpy/install_release.sh
WORKDIR /

# installing lxterminal
RUN apt install -y lxterminal

# adding new user for device connections, its uid is used in the script start.sh
RUN useradd -m webconnuser

CMD ["/bin/sh", "/mounted-scripts/start.sh"]
